baseURL = "https://protiumx.dev/blog/"
languageCode = "en-us"
title = "protiumx blog"
theme = "hello-friend-ng"

paginate = 10

disableRSS     = false
disableSitemap = false
disable404     = false
enableEmoji     = true
enableRobotsTXT = true
defaultTheme = "light"
PygmentsStyle = "monokai"

[author]
  name = "Brian Mayo"

[permalinks]
  posts = "/posts/:title/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-22-01"
  dateformNumTime = "2006-22-01"

  # Subtitle for home
  homeSubtitle = "a simple dev blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  EnableThemeToggle = true

  # Metadata mostly used in document's head
  description = "protiumx dev blog"
  keywords = "protium, protiumx, brian mayo, blog, software, engineering, rust, golang, typescript, javascript, development"
  images = ["./static/android-chrome-512x512.png"]

[params.footer]
  trademark = true
  rss = true
  copyright = true
  author = true

  topText = []
  bottomText = []

[[params.social]]
  name = "github"
  url = "https://github.com/protiumx/"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/bdmayo/"

[params.logo]
    logoText     = "$ cat protiumx/blog/*"
    logoHomeLink = "/"
    logoCursorColor = "#c7157a"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[menu]  
  [[menu.main]]
    identifier = "posts"
    name       = "posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "https://protiumx.dev"
  [[menu.main]]
    identifier = "github"
    name       = "github"
    url        = "https://github.com/protiumx"

[languages]
  [languages.en]   
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
